### Post Solicitacoes
POST http://localhost:5000/pim/postSolicitacoes
X-Header-Token: secret_key
Content-Type: application/json

{   
    "id_solicitacao": 2, 
    "rg": "457321799", 
    "rg_data_emissao": "2017-07-10", 
    "rg_uf": "SP", 
    "endereco_logradouro": "Julieta Ceoloto", 
    "endereco_numero": "666", 
    "endereco_bairro": "Quadras Eliseos", 
    "endereco_cep": "Testado", 
    "endereco_estado": "SP", 
    "data_nascimento": "2000-08-20", 
    "cnh": "Testete", 
    "cnh_data_emissao": "2017-09-20", 
    "genero": "M",
    "data_cadastro": "2022-31-10",
    "data_modificacao": "2022-31-10",
    "data_exclusao": "",
    "data_apolice": "2022-09-03",
    "status": "S",
    "fk_id_cliente": 1
}