POST http://localhost:5000/pim/postFipe
X-Header-Token: secret_key
Content-Type: application/json

{   
    "id_carro": 1, 
    "marca": "fiat", 
    "modelo": "punto", 
    "ano": "2016", 
    "tipo": "tiposo", 
    "valor": "50000"
}